resources:
  jobs:
    pipeline_projeto:
      name: pipeline - projeto
      schedule:
        quartz_cron_expression: 40 0 13 * * ?
        timezone_id: America/Sao_Paulo
        pause_status: UNPAUSED
      tasks:
        - task_key: Bronze
          notebook_task:
            notebook_path: /Workspace/Users/karinalimaolvr@gmail.com/Atividade_land_to_bronze
            source: WORKSPACE
        - task_key: Silver
          depends_on:
            - task_key: Bronze
          notebook_task:
            notebook_path: /Workspace/Users/karinalimaolvr@gmail.com/Atividade_bronze_to_silver
            source: WORKSPACE
        - task_key: Gold
          depends_on:
            - task_key: Silver
          notebook_task:
            notebook_path: /Workspace/Users/karinalimaolvr@gmail.com/Atividade_silver_to_gold
            source: WORKSPACE
      queue:
        enabled: true
      performance_target: PERFORMANCE_OPTIMIZED
